Repository SSH-key-rotation-AWS/key-switcheroo, pull requests merged in 2023-07, with the labels that each got.

#65 Build python package
  .gitignore
  bash.sh
  poetry.lock
  poetry.toml
  pyproject.toml
  requirements.txt
  switcheroo/__init__.py
  switcheroo/custom_keygen.py
  switcheroo/publisher/__init__.py
  switcheroo/publisher/__main__.py
  switcheroo/publisher/key_publisher.py
  switcheroo/server/__init__.py
  switcheroo/server/data_stores.py
  switcheroo/server/retrieve_public_keys.py
  switcheroo/server/server.py
  switcheroo/util.py
  tests/__init__.py
  tests/end_to_end/test_publish_and_read.py
  tests/unit/publisher/test_local_publisher.py
  tests/unit/publisher/test_s3_publisher.py
  tests/unit/server/test_local.py
  tests/unit/server/test_remote.py
Labels: enhancement

#68 Generate keys with metadata
  switcheroo/custom_keygen.py
  switcheroo/publisher/key_publisher.py
  switcheroo/server/data_stores.py
  switcheroo/server/retrieve_public_keys.py
  tests/end_to_end/test_publish_and_read.py
  tests/unit/publisher/test_local_publisher.py
  tests/unit/publisher/test_s3_publisher.py
  tests/unit/server/test_local.py
  tests/unit/server/test_remote.py
Labels: enhancement

#74 New __main__.py for retriever argparse
  switcheroo/server/__main__.py
Labels: enhancement

#73 Various improvements (code duplication, pathlib)
  switcheroo/custom_keygen.py
  switcheroo/data_store/__init__.py
  switcheroo/data_store/data_stores.py
  switcheroo/data_store/s3.py
  switcheroo/paths.py
  switcheroo/publisher/key_publisher.py
  switcheroo/server/data_stores.py
  switcheroo/server/retrieve_public_keys.py
  switcheroo/server/server.py
  switcheroo/util.py
  tests/end_to_end/test_publish_and_read.py
  tests/unit/publisher/test_local_publisher.py
  tests/unit/publisher/test_s3_publisher.py
  tests/unit/server/test_local.py
  tests/unit/server/test_remote.py
Labels: bug, enhancement

#76 Ssh executables argparse integration
  pyproject.toml
  switcheroo/data_store/data_stores.py
  switcheroo/data_store/s3.py
  switcheroo/publisher/__main__.py
  switcheroo/server/__main__.py
  switcheroo/server/retrieve_public_keys.py
  switcheroo/server/server.py
Labels: enhancement

#78 KeyNotFoundException
  switcheroo/data_store/data_stores.py
  switcheroo/data_store/s3.py
  switcheroo/exceptions.py
  switcheroo/server/__main__.py
Labels: enhancement

#77 Opener and pencil
  switcheroo/data_store/data_stores.py
  switcheroo/util.py
Labels: enhancement

#79 Quick easy fixes from friday review
  switcheroo/custom_keygen.py
  switcheroo/data_store/data_stores.py
  switcheroo/data_store/s3.py
  switcheroo/exceptions.py
  switcheroo/publisher/__main__.py
  switcheroo/publisher/key_publisher.py
  switcheroo/server/__main__.py
  switcheroo/server/server.py
  switcheroo/util.py
  tests/unit/publisher/test_local_publisher.py
  tests/unit/publisher/test_s3_publisher.py
  tests/unit/server/test_local.py
Labels: enhancement

#70 Tentative program documentation
  README.md
Labels: documentation

#84 Abstractioned API
  poetry.lock
  pyproject.toml
  switcheroo/base/__init__.py
  switcheroo/base/data_store/__init__.py
  switcheroo/base/data_store/s3.py
  switcheroo/base/data_store/util.py
  switcheroo/base/exceptions/s3.py
  switcheroo/base/serializer.py
  switcheroo/data_store/__init__.py
  switcheroo/data_store/data_stores.py
  switcheroo/data_store/s3.py
  switcheroo/exceptions.py
  switcheroo/paths.py
  switcheroo/publisher/key_publisher.py
  switcheroo/ssh/__init__.py
  switcheroo/ssh/data_org/__init__.py
  switcheroo/ssh/data_org/publisher/__init__.py
  switcheroo/ssh/data_org/publisher/s3.py
  switcheroo/ssh/data_org/retriever/__init__.py
  switcheroo/ssh/data_org/retriever/s3.py
  switcheroo/ssh/data_stores/__init__.py
  switcheroo/ssh/exceptions.py
  switcheroo/ssh/objects/__init__.py
  switcheroo/ssh/objects/key.py
  switcheroo/ssh/scripts/__init__.py
  switcheroo/ssh/scripts/publish.py
  switcheroo/ssh/scripts/retrieve.py
  switcheroo/ssh/server/__init__.py
  switcheroo/ssh/server/server.py
  switcheroo/util.py
  tests/end_to_end/test_publish_and_read.py
  tests/unit/publisher/test_local_publisher.py
  tests/unit/publisher/test_s3_publisher.py
  tests/unit/server/test_local.py
  tests/unit/server/test_remote.py
  tests/util/__init__.py
  tests/util/s3.py
Labels: enhancement

#88 Fixed port selector bug
  switcheroo/util.py
Labels: bug

#91 Dont-copy-retrieval-script
  .gitignore
  switcheroo/ssh/server/__init__.py
  tests/switcheroo_ssh/end_to_end/test_publish_and_read.py
  tests/switcheroo_ssh/server.py
  tests/switcheroo_ssh/unit/server/test_local.py
  tests/switcheroo_ssh/unit/server/test_remote.py
  tests/test_cloud_watch/test_file_publish_apiI.py
  tools/dev-bootstrap.sh
Labels: enhancement

#94 Moved cloudwatch api tests to use temp files
  tests/test_cloud_watch/file_metric_publisher.py
  tests/test_cloud_watch/test_file_publish_api.py
Labels: bug

#97 Some-more-ssh-tests
  tests/switcheroo_ssh/conftest.py
  tests/switcheroo_ssh/end_to_end/test_publish_and_read.py
Labels: enhancement

#98 Organized PyTest fixtures into submodules to separate between ssh testing and (future) base testing
  tests/switcheroo/__init__.py
  tests/switcheroo/conftest.py
  tests/switcheroo/ssh/__init__.py
  tests/switcheroo/ssh/conftest.py
  tests/switcheroo/ssh/end_to_end/__init__.py
  tests/switcheroo/ssh/end_to_end/test_publish_and_read.py
  tests/switcheroo/ssh/server.py
  tests/switcheroo/ssh/unit/__init__.py
  tests/switcheroo/ssh/unit/publisher/__init__.py
  tests/switcheroo/ssh/unit/publisher/test_local_publisher.py
  tests/switcheroo/ssh/unit/publisher/test_s3_publisher.py
  tests/switcheroo/ssh/unit/server/__init__.py
  tests/switcheroo/ssh/unit/server/test_local.py
  tests/switcheroo/ssh/unit/server/test_remote.py
Labels: enhancement

#100 Moved FilePublisher into the main api, made some improvements
  metric_system/functions/exceptions.py
  metric_system/functions/file_metric_publisher.py
  tests/test_cloud_watch/file_metric_publisher.py
  tests/test_cloud_watch/test_file_publish_api.py
Labels: bug, enhancement

#103 Remove-unused-parameters
  metric_system/functions/aws_metric_publisher.py
  metric_system/functions/file_metric_publisher.py
Labels: enhancement

#107 Metric-api-retrieve
  metric_system/functions/aws_metric_publisher.py
  metric_system/functions/file_metric_publisher.py
  metric_system/functions/metric.py
  tests/test_cloud_watch/cloudwatch/__init__.py
  tests/test_cloud_watch/cloudwatch/conftest.py
  tests/test_cloud_watch/cloudwatch/test_cloudwatch_publish.py
  tests/test_cloud_watch/retrievers/__init__.py
  tests/test_cloud_watch/retrievers/cloudwatch.py
  tests/test_cloud_watch/test_file_publish_api.py
Labels: enhancement

#109 Broaden expected max time from 2s to 3
  tests/test_cloud_watch/cloudwatch/test_cloudwatch_publish.py
Labels: bug

#114 Base-api-tests
  tests/switcheroo/base/__init__.py
  tests/switcheroo/base/conftest.py
  tests/switcheroo/base/resources/__init__.py
  tests/switcheroo/base/resources/module1.py
  tests/switcheroo/base/resources/module2.py
  tests/switcheroo/base/test_common_datastore.py
  tests/switcheroo/base/test_file_datastore.py
  tests/switcheroo/base/test_s3_datastore.py
Labels: enhancement

#116 Fixed typo bug in metric test
  tests/test_cloud_watch/cloudwatch/test_metrics.py
Labels: bug

#117 Added documentation for base api and moved a function to be private
  switcheroo/base/data_store/__init__.py
  switcheroo/base/data_store/s3.py
  switcheroo/base/data_store/util.py
  switcheroo/base/exceptions/s3.py
  switcheroo/base/serializer.py
Labels: documentation, enhancement

#120 Integration tests
  README.md
  switcheroo/ssh/__init__.py
  switcheroo/ssh/data_org/publisher/__init__.py
  tests/switcheroo/ssh/conftest.py
  tests/switcheroo/ssh/end_to_end/test_publish_and_read.py
  tests/switcheroo/ssh/integration/conftest.py
  tests/switcheroo/ssh/integration/test_aws_metric_publishing.py
  tests/switcheroo/ssh/integration/test_file_metric_publishing.py
  tests/switcheroo/ssh/unit/publisher/test_local_publisher.py
  tests/switcheroo/ssh/unit/publisher/test_s3_publisher.py
  tests/switcheroo/ssh/unit/server/test_local.py
  tests/switcheroo/ssh/unit/server/test_remote.py
Labels: test

#124 Fix-dist-package
  poetry.lock
  pyproject.toml
Labels: bug

#118 Documentation for the ssh part
  switcheroo/ssh/__init__.py
  switcheroo/ssh/data_stores/__init__.py
  switcheroo/ssh/exceptions.py
  switcheroo/ssh/objects/key.py
Labels: documentation

#125 Aws-profiles
  aws_profiles/__init__.py
  aws_profiles/exceptions.py
  aws_profiles/profile.py
  poetry.lock
  pyproject.toml
  tests/aws_profiles/__init__.py
  tests/aws_profiles/conftest.py
  tests/aws_profiles/test_profile_manager.py
Labels: enhancement

#126 Added configure script
  aws_profiles/__init__.py
  pyproject.toml
  switcheroo/base/__init__.py
  switcheroo/base/scripts/configure.py
Labels: enhancement

#128 Integrate-profile-api
  metric_system/functions/aws_metric_publisher.py
  switcheroo/base/data_store/s3.py
  switcheroo/ssh/data_org/publisher/s3.py
  switcheroo/ssh/data_org/retriever/s3.py
  switcheroo/ssh/scripts/__init__.py
  switcheroo/ssh/scripts/publish.py
  switcheroo/ssh/scripts/retrieve.py
  tests/conftest.py
  tests/switcheroo/base/conftest.py
  tests/switcheroo/conftest.py
  tests/switcheroo/ssh/conftest.py
  tests/switcheroo/ssh/integration/conftest.py
  tests/test_cloud_watch/cloudwatch/conftest.py
  tests/test_cloud_watch/conftest.py
  tests/test_cloud_watch/retrievers/cloudwatch.py
Labels: enhancement

#130 Improve argparse
  README.md
  metric_system/functions/file_metric_publisher.py
  switcheroo/base/data_store/__init__.py
  switcheroo/base/data_store/exceptions.py
  switcheroo/ssh/scripts/custom_argument_exceptions.py
  switcheroo/ssh/scripts/publish.py
  switcheroo/ssh/scripts/retrieve.py
  tests/switcheroo/ssh/unit/publisher/test_cli.py
  tests/switcheroo/ssh/unit/retriever/test_cli.py
Labels: enhancement

#136 Jenkins
  .gitignore
  Jenkinsfile
  bash.sh
  jenkins_pipeline/github_api_tag_manager.py
  poetry.lock
  pyproject.toml
  terraform-environments/aws_access_key.xml
  terraform-environments/aws_secret_access_key.xml
  terraform-environments/config.xml
  terraform-environments/ec2_instance.tf
  terraform-environments/github_credentials.xml
  terraform-environments/github_pat.xml
  terraform-environments/hosts-user-data.sh
  terraform-environments/instance.tf
  terraform-environments/main.tf
  terraform-environments/pypi_api_token.xml
  terraform-environments/setup.groovy
  terraform-environments/startup.sh
  tests/switcheroo/ssh/server.py
  tests/test_cloud_watch/cloudwatch/test_cloudwatch_publish.py
  tools/git_hooks/pre-commit
  tools/git_hooks/pre-commit-bash
Labels: enhancement

#137 fix jenkins file
  Jenkinsfile
Labels: enhancement

#140 Allows deletion of only profile; allow invalid profiles to be loaded, then immediately forgotten
  aws_profiles/__init__.py
  tests/aws_profiles/conftest.py
  tests/aws_profiles/test_profile_manager.py
Labels: bug

#144 Removed psutil, moved paramiko to be a dev dependency only
  poetry.lock
  pyproject.toml
Labels: enhancement

#142 Add documentation for switcheroo_configure
  README.md
Labels: documentation

#146 Clarify hostname, move other docs
  README.md
Labels: documentation, enhancement

#147 Fix instructions on how to set up sshd
  README.md
Labels: documentation

#148 Multiple Testing Improvements
  tests/aws_profiles/test_profile_manager.py
  tests/conftest.py
  tests/switcheroo/conftest.py
  tests/switcheroo/ssh/conftest.py
  tests/switcheroo/ssh/end_to_end/test_publish_and_read.py
  tests/switcheroo/ssh/server.py
  tests/switcheroo/ssh/unit/publisher/test_cli.py
  tests/switcheroo/ssh/unit/retriever/__init__.py
  tests/switcheroo/ssh/unit/retriever/test_cli.py
  tests/switcheroo/ssh/unit/retriever/test_local.py
  tests/switcheroo/ssh/unit/retriever/test_remote.py
  tests/switcheroo/ssh/unit/server/test_local.py
  tests/switcheroo/ssh/unit/server/test_remote.py
Labels: bug, enhancement
